---

- name: Pull hendrix war file from S3 bucket
  s3_sync:
    bucket: hendrix-war-deploy 
    file_root: roles/app-deploy/files/
    file_change_strategy: force
    permission: public-read
    include: "*.war"
    exclude: ".*"

- name: Deploy Static files, Step 1
  s3:
    mode: list
    bucket: hendrix-static-deploy
    prefix: hendrix-static-deploy/
  register: s3_bucket_items

- name: Deploy Static files, Step 2
  s3:
    mode: get
    bucket: hendrix-static-deploy
    object: "{{ item }}"
    dest: "roles/app-deploy/files/"
    permission: public-read
  with_items: s3_bucket_items.s3_keys

- name: Deploy the hendrix  war file
  jboss:
    src: "{{hendrix_build_war_name}}".war
    deployment: "{{hendrix_deploy_war_name}}".war
    state: present

- name: Deploy static assets to data directory
  synchronize:
    src: roles/app-deploy/files/data
    dest: /apps/wildfly/standalone/
    delete: yes
    recursive: yes

